---
- name: Check if Makefile exists
  local_action: stat path="{{ ansistrano_deploy_from }}/Makefile"
  register: Makefile

- name: Run 'make build'
  local_action: command make build
  args:
    chdir: "{{ ansistrano_deploy_from }}"
  when: Makefile.stat.exists is defined and Makefile.stat.exists == True