---

- local_action:
    module: slack
    token: "{{ notification_slack_token }}"
    username: "Samson deployment"
    msg:   ":airplane_arriving: Finished deployment of {{ lookup('env','PROJECT_NAME') }}/{{ lookup('env','STAGE') }} (revision: {{ lookup('env','REVISION') }}, duration: {{ lookup('env','DEPLOYMENT_DURATION') }})"
    color: "good"
    channel: "{{ notification_slack_channel | default(omit) }}"
  when: notification_slack_token is defined and notification_slack_token != ""
