---

- name: Run finalization tasks
  command: "{{ item }}"
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
  with_items: deployment_finalize_tasks
  when: deployment_finalize_tasks is defined
